development:
  mailer_username:        <%= ENV["MAILER_USERNAME"] %>
  mailer_password:        <%= ENV["MAILER_PASSWORD"] %>
  mailer_address:         <%= ENV["MAILER_ADDRESS"] %>
  mailer_domain:          <%= ENV["MAILER_DOMAIN"] %>
  mailer_port:            <%= ENV["MAILER_PORT"] %>
  mailer_authentication:  <%= ENV["MAILER_AUTHENTICATION"] %>
  admin_email:            <%= ENV["ADMIN_EMAIL"] %>
  admin_password:         <%= ENV["ADMIN_PASSWORD"] %>
